services:

  postgres:
    container_name: postgres
    image: postgres:16.8
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      - CREATE_DATABASES=currency-service,payment-service
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}
    command: postgres -c max_connections=200 -c max_prepared_transactions=100
    volumes:
      - bank-pg-data:/var/lib/postgresql/data
      - ./env/docker/postgres/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER:-postgres}", "-d", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - bank-network
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.6
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT:-5433}:80"
    volumes:
      - bank-pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-mymail@mail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-12345}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/misc/ping || exit -1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bank-network

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass redis
    volumes:
      - bank-redis-data:/data

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.2
    restart: unless-stopped
    expose:
      - 2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - bank-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.2
    restart: unless-stopped
    ports:
      - "9092:9092"
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    networks:
      - bank-network

volumes:
  bank-pg-data:
  bank-pgadmin-data:
  bank-redis-data:
  kafka-ui-data:

networks:
  bank-network:
    driver: bridge